# Generated by Django 5.1.4 on 2025-01-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0002_remove_schema_user_dataschema_datacolumn_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datacolumn",
            old_name="date_type",
            new_name="data_type",
        ),
    ]
