# Generated by Django 5.1.4 on 2025-01-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0003_rename_date_type_datacolumn_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacolumn",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("full_name", "Full Name"),
                    ("job", "Job"),
                    ("email", "Email"),
                    ("domain_name", "Domain Name"),
                    ("phone_number", "Phone Number"),
                    ("company_name", "Company Name"),
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("address", "Address"),
                    ("date", "Date"),
                ],
                max_length=20,
            ),
        ),
    ]
